config/routes.rb
Tecnisolar::Application.routes.draw do
  

  resources :categories

  root :to => "home#index"

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"
  get "account_settings" => "authentication#account_settings"
  post "account_settings" => "authentication#set_account_info"

  get "change_password" => "authentication#change_password"
  get "forgot_password" => "authentication#forgot_password"
  
  get "password_sent" => "authentication#password_sent"

  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"

  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"

  match 'products/:id/add_to_cart' => 'products#add_to_cart', :as => :add_to_cart
  match 'products/:id/remove_from_cart' => 'products#remove_from_cart', :as => :remove_from_cart
  match 'products/clear_cart' => 'products#clear_cart', :as => :clear_cart
  match 'products/purchase' => 'products#purchase', :as => :purchase
  match 'products/end_purchase' => 'products#end_purchase', :as => :end_purchase
  match 'products/listing' => 'products#listing', :as => :listing
  match 'products/thank_you' => 'products#thank_you', :as => :thank_you

  match 'ofrecemos' => 'home#ofrecemos', :as => :ofrecemos
  match 'contacto' => 'home#contacto', :as => :contacto
  match 'agua_caliente_sanitaria' => 'home#agua_caliente_sanitaria', :as => :agua_caliente_sanitaria
  match 'calefaccion' => 'home#calefaccion', :as => :calefaccion
  match 'instalaciones_hoteleras_campings' => 'home#instalaciones_hoteleras_campings', :as => :instalaciones_hoteleras_campings
  match 'climatizacion_piscinas' => 'home#climatizacion_piscinas', :as => :climatizacion_piscinas
  match 'instalaciones_agricolas' => 'home#instalaciones_agricolas', :as => :instalaciones_agricolas
  match 'calderas_biomasa' => 'home#calderas_biomasa', :as => :calderas_biomasa
  match 'form' => 'home#form', :as => :form

  match 'submit_mail' => 'home#submit_mail', :as => :submit_mail
  match 'gracias' => 'home#gracias', :as => :gracias

  resources :products
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_hash, :password_salt, :username, :password, :password_confirmation, :new_password, :new_password_confirmation, :admin
  attr_accessor :password, :new_password
  before_save :encrypt_password
  has_and_belongs_to_many :roles

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :on => :create
  validates_presence_of :username, :on => :create
  validates_uniqueness_of :email
  validates_uniqueness_of :username

  # change password
  validates_confirmation_of :new_password, :if => Proc.new {|user| !user.new_password.nil? && !user.new_password.empty? }

  def self.authenticate_by_email(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def self.authenticate_by_username(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
       nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def admin?
    admin == true
  end

  def role?(role_name)
    roles.any?{|r| r.name == role_name}
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource :class => User

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Nombre de usuario<br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    Email<br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
<p class="intro-message"><strong>Modificar usuario</strong></p>
</div>

<div id="home-content">

<%= render 'form' %>

</div>
<div id="product_links">
  <%if current_user && current_user.admin?%>
  Opciones:
  <%= link_to 'Listado de usuarios', users_path %> /
  <%=link_to 'Panel', :controller => 'authentication', :action => 'sign_in'%>
  <%end%>
</div>
<HR>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>

app/views/users/index.html.erb
<div id="home-content-wrapper-bar">

<div id="separator"></div>
<div id="home-content-header-thinest">
<p class="intro-message"><strong>Listado de usuarios</strong></p>
</div>

<div id="home-content">

<table class="battle-table" border="0" width="50%">
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Modificar', edit_user_path(user) %></td>
    <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: '¿Eliminar usuario?' } %></td>
  </tr>
<% end %>
</table>

</div>
<hr> 
<div id="product_links">
<%if current_user && current_user.admin?%>
Opciones: <%= link_to 'Crear nuevo usuario', new_user_path %> / <%=link_to 'Panel', :controller => 'authentication', :action => 'sign_in'%>
<%end%>
</div>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password hash:</b>
  <%= @user.password_hash %>
</p>

<p>
  <b>Password salt:</b>
  <%= @user.password_salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>