config/routes.rb
Tecnisolar::Application.routes.draw do
  

  resources :categories

  root :to => "home#index"

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"
  get "account_settings" => "authentication#account_settings"
  post "account_settings" => "authentication#set_account_info"

  get "change_password" => "authentication#change_password"
  get "forgot_password" => "authentication#forgot_password"
  
  get "password_sent" => "authentication#password_sent"

  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"

  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"

  match 'products/:id/add_to_cart' => 'products#add_to_cart', :as => :add_to_cart
  match 'products/:id/remove_from_cart' => 'products#remove_from_cart', :as => :remove_from_cart
  match 'products/clear_cart' => 'products#clear_cart', :as => :clear_cart
  match 'products/purchase' => 'products#purchase', :as => :purchase
  match 'products/end_purchase' => 'products#end_purchase', :as => :end_purchase
  match 'products/listing' => 'products#listing', :as => :listing
  match 'products/thank_you' => 'products#thank_you', :as => :thank_you

  match 'ofrecemos' => 'home#ofrecemos', :as => :ofrecemos
  match 'contacto' => 'home#contacto', :as => :contacto
  match 'agua_caliente_sanitaria' => 'home#agua_caliente_sanitaria', :as => :agua_caliente_sanitaria
  match 'calefaccion' => 'home#calefaccion', :as => :calefaccion
  match 'instalaciones_hoteleras_campings' => 'home#instalaciones_hoteleras_campings', :as => :instalaciones_hoteleras_campings
  match 'climatizacion_piscinas' => 'home#climatizacion_piscinas', :as => :climatizacion_piscinas
  match 'instalaciones_agricolas' => 'home#instalaciones_agricolas', :as => :instalaciones_agricolas
  match 'calderas_biomasa' => 'home#calderas_biomasa', :as => :calderas_biomasa
  match 'form' => 'home#form', :as => :form

  match 'submit_mail' => 'home#submit_mail', :as => :submit_mail
  match 'gracias' => 'home#gracias', :as => :gracias

  resources :products
  resources :users

end

app/controllers/authentication_controller.rb
# encoding: UTF-8

class AuthenticationController < ApplicationController

  def sign_in
    @user = User.new
  end

  def login
    username_or_email = params[:user][:username]
    password = params[:user][:password]

    if username_or_email.rindex('@')
      email=username_or_email
      user = User.authenticate_by_email(email, password)
    else
      username=username_or_email
      user = User.authenticate_by_username(username, password)
    end

    if user
      session[:user_id] = user.id
      flash[:notice] = 'Bienvenido.'
      redirect_to :products
      #redirect_to :root
    else
      flash.now[:error] = 'Usuario desconocido. Verifica nombre de usuarios y contraseña.'
      render :action => "sign_in"
    end

  end

  def signed_out
    session[:user_id] = nil
    #flash[:notice] = "You have been signed out."
    flash[:notice] = "Se cerró la sesión."
    redirect_to :root
  end
  
  def new_user
     @user = User.new
  end
 
  def register
    @user = User.new(params[:user])
  
    if @user.valid?
      @user.save
      UserMailer.welcome_email(@user).deliver
      session[:user_id] = @user.id
      flash[:notice] = 'Bienvenido.'
      redirect_to :root
    else
      render :action => "new_user"
    end
  end

  def account_settings
     @user = current_user
  end

  def set_account_info
    old_user = current_user
    
    # Does it match with current password?
    @user = User.authenticate_by_username(old_user.username, params[:user][:password])

    # verify
    if @user.nil?
      @user = current_user
      @user.errors[:password] = "Contraseña errónea"
    else
      # If there is a new_password value, then we need to update the password.
      if !params[:user][:new_password].nil? && !params[:user][:new_password].empty?
        #raise @user.email
        @user.password = params[:user][:new_password]
        @user.save!
        #raise @user.id
        flash[:notice] = 'Se modificó la contraseña'
        render :action => 'sign_in'
      else
        @user.errors[:new_password] = 'Debe indicar algo como contraseña'
        render :action => "account_settings"
      end

    end
  end

  # get
  def forgot_password
    @user = User.new
  end

  # put
  def send_password_reset_instructions
    username_or_email = params[:user][:username]

    if username_or_email.rindex('@')
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end

    if user
      user.password_reset_token = SecureRandom.urlsafe_base64
      user.password_expires_after = 10.hours.from_now
      user.save
      UserMailer.reset_password_email(user).deliver
      flash[:notice] = 'Se han enviado por email las instrucciones para recuperar la contraseña.'
      redirect_to :sign_in
    else
      @user = User.new
      # put the previous value back.
      @user.username = params[:user][:username]
      @user.errors[:username] = 'no es un usuario registrado.'
      render :action => "forgot_password"
    end
  end

  # HTTP get
  def password_reset
    token = params.first[0]
    @user = User.find_by_password_reset_token(token)

    if @user.nil?
      flash[:error] = 'No ha sido solicitado el cambio de contraseña de este usuario.'
      redirect_to :root
      return
    end

    if @user.password_expires_after < DateTime.now
      clear_password_reset(@user)
      @user.save
      flash[:error] = 'La solicitud de camnio de contraseña ha caducado. Por favor, solicítalo de nuevo.'
      redirect_to :forgot_password
    end
  end

  # HTTP put
  def new_password
    username = params[:user][:username]
    @user = User.find_by_username(username)

    if verify_new_password(params[:user])
      @user.update_attributes(params[:user])
      @user.password = @user.new_password

      if @user.valid?
        clear_password_reset(@user)
        @user.save
        flash[:notice] = 'Se ha modificado la contraseña. Acceda con la nueva contraseña.'
        redirect_to :sign_in
      else
        render :action => "password_reset"
      end
    else
      @user.errors[:new_password] = 'La contraseña no puede estar en blanco y debe coincidir en ambos campos.'
      render :action => "password_reset"
    end
  end

  private

   def clear_password_reset(user)
     user.password_expires_after = nil
     user.password_reset_token = nil
   end

   def verify_new_password(passwords)
     result = true

     if passwords[:new_password].blank? || (passwords[:new_password] != passwords[:new_password_confirmation])
       result = false
     end

     result
   end

end

app/views/authentication/account_settings.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
<p class="intro-message"><strong>Cambiar contraseña</strong></p>
</div>

<div id="home-content">
<%= form_for @user, :as => :user, :url => account_settings_path, :method => :post do |f| %>
  <p>
    <%= f.label 'Contraseña actual:' %><br/>
    <%= f.password_field :password %>
    <%= show_field_error(@user, :password) %>
  </p>
  <p>
    <%= f.label 'Nueva contraseña:' %><br/>
    <%= f.password_field :new_password %>
    <%= show_field_error(@user, :new_password) %>
  </p>
  <p>
    <%= f.label 'Confirmar contraseña:' %><br/>
    <%= f.password_field :new_password_confirmation %>
  </p>
  <p>
    <%= f.submit 'Modificar' %>
  </p>
<% end %>
</div>
<div id="product_links">
  <%if current_user && current_user.admin?%>
  Opciones:
  <%= link_to 'Usuarios', users_path %> /
  <%= link_to 'Productos', products_path %> /
  <%= link_to 'Categorías', categories_path %>
  <%end%>
</div>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>

app/views/authentication/forgot_password.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
<p class="intro-message"><strong>Resetear contraseña</strong></p>
</div>

<div id="home-content">
<%= form_for @user, :as => :user, :url => forgot_password_path, :method => :put do |f| %>
  <p>
    <%= f.label 'Nombre de usuario o email:' %><br/>
    <%= f.text_field :username %>
    <%= show_field_error(@user, :username) %>
  </p>
  <p>
    <%= f.submit 'Enviar instrucciones' %>
  </p>
<% end %>
</div>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>

app/views/authentication/new_user.html.erb
<p>Sign Up</p>
<%= form_for @user, :as => :user, :url => new_user_path, :method => :post do |f| %>
  <p>
    <%= f.label 'username:' %><br/>
    <%= f.text_field :username %>
    <%= show_field_error(@user, :username) %>
  </p>
  <p>
    <%= f.label 'email:' %><br/>
    <%= f.text_field :email %>
    <%= show_field_error(@user, :email) %>
  </p>
  <p>
    <%= f.label 'password:' %><br/>
    <%= f.password_field :password %>
    <%= show_field_error(@user, :password) %>
  </p>
  <p>
    <%= f.label 'password confirmation:' %><br/>
    <%= f.password_field :password_confirmation %>
    <%= show_field_error(@user, :password_confirmation) %>
  </p>
  <p>
    <%= f.submit 'Sign Up' %>&nbsp;&nbsp;&nbsp;
  </p>
<% end %>

app/views/authentication/password_reset.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
<p class="intro-message"><strong>Nueva contraseña</strong></p>
</div>

<div id="home-content">
<%= form_for @user, :as => :user, :url => password_reset_path, :method => :put do |f| %>
  <p>
    <%= @user.username %> ha solicitado el cambio de contraseña. Entra una nueva contraseña:
  </p>
  <p>
    <%= f.label 'Nueva contraseña:' %><br/>
    <%= f.password_field :new_password %>
    <%= show_field_error(@user, :new_password) %>
  </p>
  <p>
    <%= f.hidden_field :username %>
    <%= f.label 'Repite la contraseña:' %><br/>
    <%= f.password_field :new_password_confirmation %>
    <%= show_field_error(@user, :new_password_confirmation) %>
  </p>
  <p>
    <%= f.submit 'Modificar' %>
  </p>
<% end %>
</div>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>

app/views/authentication/sign_in.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
<p class="intro-message"><strong>Acceso</strong></p>
</div>

<div id="home-content">
<%= form_for @user, :as => :user, :url => sign_in_path(@user) do |f| %>
  <p>
    <%= f.label 'Nombre de usuario o e-mail:' %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label 'Contraseña:' %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit 'Entrar' %>&nbsp;&nbsp; 
    <%if current_user.nil?%>
    <%= link_to 'Olvidé mi contraseña', :forgot_password %>
    <%end%>
  </p>
<% end %>
</div>
<div id="product_links">
  <%if current_user && current_user.admin?%>
  Opciones:
  <%= link_to 'Usuarios', users_path %> /
  <%= link_to 'Productos', :controller => 'products', :action => 'listing' %> /
  <%= link_to 'Categorías', categories_path %> /
  <%= link_to 'Cambiar mi password', account_settings_path %>
  <%end%>
</div>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>