config/routes.rb
Tecnisolar::Application.routes.draw do
  

  resources :categories

  root :to => "home#index"

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"
  get "account_settings" => "authentication#account_settings"
  post "account_settings" => "authentication#set_account_info"

  get "change_password" => "authentication#change_password"
  get "forgot_password" => "authentication#forgot_password"
  
  get "password_sent" => "authentication#password_sent"

  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"

  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"

  match 'products/:id/add_to_cart' => 'products#add_to_cart', :as => :add_to_cart
  match 'products/:id/remove_from_cart' => 'products#remove_from_cart', :as => :remove_from_cart
  match 'products/clear_cart' => 'products#clear_cart', :as => :clear_cart
  match 'products/purchase' => 'products#purchase', :as => :purchase
  match 'products/end_purchase' => 'products#end_purchase', :as => :end_purchase
  match 'products/listing' => 'products#listing', :as => :listing
  match 'products/thank_you' => 'products#thank_you', :as => :thank_you

  match 'ofrecemos' => 'home#ofrecemos', :as => :ofrecemos
  match 'contacto' => 'home#contacto', :as => :contacto
  match 'agua_caliente_sanitaria' => 'home#agua_caliente_sanitaria', :as => :agua_caliente_sanitaria
  match 'calefaccion' => 'home#calefaccion', :as => :calefaccion
  match 'instalaciones_hoteleras_campings' => 'home#instalaciones_hoteleras_campings', :as => :instalaciones_hoteleras_campings
  match 'climatizacion_piscinas' => 'home#climatizacion_piscinas', :as => :climatizacion_piscinas
  match 'instalaciones_agricolas' => 'home#instalaciones_agricolas', :as => :instalaciones_agricolas
  match 'calderas_biomasa' => 'home#calderas_biomasa', :as => :calderas_biomasa
  match 'form' => 'home#form', :as => :form

  match 'submit_mail' => 'home#submit_mail', :as => :submit_mail
  match 'gracias' => 'home#gracias', :as => :gracias

  resources :products
  resources :users

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :id
  #belongs_to :product
  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

  #scope :not_empty, joins(:products) #.available #.having('available=1')
  #scope :not_empty, where(Product.categories.count => 0)
  #scope :not_empty,  joins(:categories).
  #scope :not_empty, joins(:products).select('distinct categories.*')
  def self.not_empty
  	c = Category.joins(:products).select('distinct categories.*').where('products.available=1')
  	c
  end

  def st_products_uom #units of measure
    count = self.products.count
    uom = count == 1 ? "producto" : "productos"
    "#{count} #{uom}"
  end
end

app/controllers/categories_controller.rb
# encoding: UTF-8

class CategoriesController < ApplicationController

  load_and_authorize_resource :class => Category

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Categoría creada.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "index" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Categoría creada.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
<p class="intro-message"><strong>Edición de categorías</strong></p>
</div>

<div id="home-content">

<%= render 'form' %>

</div>
<div id="product_links">
  <%if current_user && current_user.admin?%>
  Opciones:
  <%= link_to 'Listado de categorías', categories_path %> /
  <%=link_to 'Panel', :controller => 'authentication', :action => 'sign_in'%>
  <%end%>
</div>
<HR>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>

app/views/categories/index.html.erb
<div id="home-content-wrapper-bar">

<div id="separator"></div>
<div id="home-content-header-thinest">
<p class="intro-message"><strong>Listado de Categorías</strong></p>
</div>

<div id="home-content">

<table class="battle-table" border="0" width="50%">
  <tr>
    <th>Descripción</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.description %> (<%= link_to category.st_products_uom, products_path(:category_id => category.id) %>)</td>
    <td><%= link_to 'Modificar', edit_category_path(category) %></td>
    <td><%= link_to 'Eliminar', category, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
  </tr>
<% end %>
</table>

</div>
<hr> 
<div id="product_links">
<%if current_user && current_user.admin?%>
Opciones: <%= link_to 'Nueva Categoría', new_category_path %> / <%=link_to 'Panel', :controller => 'authentication', :action => 'sign_in'%>
<%end%>
</div>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>

app/views/categories/new.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
<p class="intro-message"><strong>Nueva categoría</strong></p>
</div>

<div id="home-content">
<%= render 'form' %>
</div>

<div id="product_links">
  <%if current_user && current_user.admin?%>
  Opciones:
  <%= link_to 'Listado de categorías', categories_path %> /
  <%=link_to 'Panel', :controller => 'authentication', :action => 'sign_in'%>
  <%end%>
</div>
<hr>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>