config/routes.rb
Tecnisolar::Application.routes.draw do
  

  resources :categories

  root :to => "home#index"

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"
  get "signed_out" => "authentication#signed_out"
  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"
  get "account_settings" => "authentication#account_settings"
  post "account_settings" => "authentication#set_account_info"

  get "change_password" => "authentication#change_password"
  get "forgot_password" => "authentication#forgot_password"
  
  get "password_sent" => "authentication#password_sent"

  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"

  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"

  match 'products/:id/add_to_cart' => 'products#add_to_cart', :as => :add_to_cart
  match 'products/:id/remove_from_cart' => 'products#remove_from_cart', :as => :remove_from_cart
  match 'products/clear_cart' => 'products#clear_cart', :as => :clear_cart
  match 'products/purchase' => 'products#purchase', :as => :purchase
  match 'products/end_purchase' => 'products#end_purchase', :as => :end_purchase
  match 'products/listing' => 'products#listing', :as => :listing
  match 'products/thank_you' => 'products#thank_you', :as => :thank_you

  match 'ofrecemos' => 'home#ofrecemos', :as => :ofrecemos
  match 'contacto' => 'home#contacto', :as => :contacto
  match 'agua_caliente_sanitaria' => 'home#agua_caliente_sanitaria', :as => :agua_caliente_sanitaria
  match 'calefaccion' => 'home#calefaccion', :as => :calefaccion
  match 'instalaciones_hoteleras_campings' => 'home#instalaciones_hoteleras_campings', :as => :instalaciones_hoteleras_campings
  match 'climatizacion_piscinas' => 'home#climatizacion_piscinas', :as => :climatizacion_piscinas
  match 'instalaciones_agricolas' => 'home#instalaciones_agricolas', :as => :instalaciones_agricolas
  match 'calderas_biomasa' => 'home#calderas_biomasa', :as => :calderas_biomasa
  match 'form' => 'home#form', :as => :form

  match 'submit_mail' => 'home#submit_mail', :as => :submit_mail
  match 'gracias' => 'home#gracias', :as => :gracias

  resources :products
  resources :users

end

app/models/product.rb
# encoding: UTF-8

class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  attr_accessible :description, :name, :price, :reference, :image, :category, :product_categories_attributes, :enable, :available
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  accepts_nested_attributes_for :product_categories, allow_destroy: true

  validates_presence_of :product_categories, :presence => true

  scope :available, :conditions => {:available => true}

  def self.filter_by_params(b_admin, params)
    if params[:category_id]
      prods = b_admin ? Category.find(params[:category_id]).products.page(params[:page]).per(8) : Category.find(params[:category_id]).products.available.page(params[:page]).per(8)
    else
      prods = b_admin ? Product.page(params[:page]).per(8) : Product.available.page(params[:page]).per(8)
    end
    #prods.available unless b_admin
  end

  #overwrites internal rails method for descriptive urls
  def to_param
    "#{id} #{name}".parameterize
  end

  def image_path
  	path = self.image.blank? ? "/public/images/no_product_image.jpg" : self.image.url 
  end

  def self.page_description(params)
    if params[:category_id]
       Category.find(params[:category_id]).description
    else
       "Productos disponibles"
    end
  end

  def st_availability
    if !available
      "NO disponible"
    else
      "Sí"
    end
  end

  def reduced_description
    description[0,150] + "..."
  end

  #http://pastebin.com/g9jt6UQ1
  def initialized_categorizations # this is the key method
    [].tap do |o|
      Category.all.each do |category|
        if c = product_categories.find { |c| c.category_id == category.id }
          o << c.tap { |c| c.enable ||= true }
        else
          o << ProductCategory.new(category: category)
        end
      end
    end
  end

  def self.IVA
    21
  end

  def self.IVA_amount(amount)
    amount * (Product.IVA / 100.00) rescue 0
  end

  def self.amount_with_tax(amount)
    amount * (1 + (Product.IVA / 100.00))
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :build_product, :only => [:new]
  before_filter :load_product, :only => [:edit]
  before_filter :build_or_load_categorization, :only => [:new, :edit]
  before_filter :process_categorizations_attrs, only: [:create, :update]

  # GET /products
  # GET /products.json
  def index
    b_admin = current_user.admin? rescue false
    @products = Product.filter_by_params(b_admin, params)
    #@products = Product.available
    
    @title = Product.page_description(params)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def listing
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @product.image = params[:image] if params[:image]
    #params[:product][:category_ids].each{|c|
    #  @product.category = c
    #}

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    @product.image = params[:image] if params[:image]

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def add_to_cart
    session[:cart] ||= Cart.new
    session[:cart] = session[:cart].add_product(params[:id])
    respond_to do |format|
       format.html {redirect_to :products}
       format.js
    end
  end

  def remove_from_cart
    session[:cart] = session[:cart].remove_product(params[:id])
    respond_to do |format|
      format.html {redirect_to :products}
      format.js
    end
  end

  def clear_cart
    session[:cart].reset
    session[:cart] = nil

    respond_to do |format|
      format.html {redirect_to :products}
      format.js
    end
  end

  def purchase
  end

  def end_purchase
      UserMailer.order_confirmation(session[:cart], params).deliver
      flash[:notice] = 'Pedido completado correctamente.'
      redirect_to :thank_you
  end

  def thank_you
     session[:cart].reset
     session[:cart] = nil
  end

  private
  def build_product
    @product = Product.new
  end

  def load_product
    @product = Product.find_by_id(params[:id])
    @product || invalid_url
  end

  def build_or_load_categorization
    Category.where('id not in (?)', @product.categories).each do |c|
      @product.product_categories.new(:category => c)
    end
  end

  def render_with_categorization(template)
    build_or_load_categorization
    render :action => template
  end

  def process_categorizations_attrs
    params[:product][:product_categories_attributes].values.each do |cat_attr|
      cat_attr[:_destroy] = true if cat_attr[:enable] != '1'
    end
  end

  # Sphinx search action
  def search
    raise "uninplemented"
    #search_input = params[:search]
    #@result = Product.search_count search_input
  end 

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_cart.html.erb
<div id="cart">
<table class="cart-table">
<tr><td><h3>Producto</h3></td><td><h3>Uds.</h3></td><td></tr>
<%amount = 0
  session[:cart].items.each_key{|prod_id|
   p = Product.find(prod_id)
   u = session[:cart].items[prod_id]
   amount += p.price * u.to_i
   %>
   <tr><td><%=p.name%></td><td><%=u%></td><td><strong><%= link_to '+', add_to_cart_path(prod_id), :remote => true %> | <%= link_to '-', remove_from_cart_path(prod_id), :remote => true %></strong></td></tr>
<%}%>
</table>
<div id="total_price">Total: <%=amount%> €</div>
</div>
<div id="product_links"><%= link_to 'Vaciar carrito', clear_cart_path, :remote => true %> - <%= link_to 'Finalizar compra', purchase_path%></div>

app/views/products/_form.html.erb
<%@product.categories.build%>
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="flash_error">
      <h2><%= pluralize(@product.errors.count, "error") %> no permite guardar este producto:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
     Nombre:<br />
     <%= f.text_field :name %>
  </div>
  <div class="field">
     Imagen:<br />
     <%= image_tag(@product.image_path, :size => "150x150")%>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    Referencia:<br />
    <%= f.text_field :reference %>
  </div>
  <div class="field">
    Precio (sin IVA):<br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    Texto descriptivo:<br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    ¿Disponible?:<br />
    <%= f.check_box :available %>
  </div>

  <!-- Categories -->
  <hr>
  <div class="field">
  Categorías:
  <%= f.fields_for :product_categories, @product.initialized_categorizations do |builder| %>
    <% category = builder.object.category %>
    <%= builder.hidden_field :category_id %>
 
    <div class="field">
      <%= builder.label :enable, category.description %> 
      <%= builder.check_box :enable %>
    </div>
 
   <% end %>
  </div>
  <!-- /Categories -->
  <div class="actions">
    <%= f.submit "Guardar"%>
  </div>
<% end %>

app/views/products/_navbar.erb
<%
@categories = Category.not_empty
first_level = 5
i = 0
arr_more = [] 
%>
<div id="nav-bar">
       <div class="left"></div>
       <ul>
          <%@categories.each{|c|
             i+=1
             if i <= first_level
               %>
                 <li><%= link_to c.description, products_path(:category_id => c.id) %></li>
               <%
             else
               arr_more << c    
             end
          }%>
       </ul>
       <%if !arr_more.empty?%>
       <div id="more-cats">
        <li><a href="#">Más v</a></li>
         <div id="nav-bar-more">
           <%arr_more.each{|cm|%>
             <li><%= link_to cm.description, products_path(:category_id => cm.id) %></li>
           <%}%>
         </div>
       </div>
       <%end%>
</div>

app/views/products/add_to_cart.js.erb
$('#asinc_cart').html('<%=j render partial: 'products/cart'%>')

app/views/products/clear_cart.js.erb
$('#asinc_cart').html('')

app/views/products/edit.html.erb
<div id="home-content-wrapper">
<!-- /home-content-header -->

  <div id="home-content">

   <h1>Modificar producto:</h1>

    <%= render 'form' %>

   </div><!-- /home-content -->

<div id="product_links">
<%= link_to 'Lista de productos', :controller => 'products', :action => 'listing' %>
</div>

</div><!-- /home-content-wrapper -->

app/views/products/index.html.erb
<div id="home-content-wrapper-bar">

<%= render "navbar" %>

<div id="separator"></div>
<div id="home-content">
<div id="home-nav">

<h1><%=@title%></h1>
<div id="separator"></div>
<table border="0" width="100%">
<% @products.in_groups_of(2,false) do |row_product| %>
  <tr>
    <% for product in row_product %>
     <td width="50%">
        <div id="product_name"><%= product.name %></div>
        <div id="product_image"><%= link_to image_tag(product.image_path, :size => "200x200"), product%></div>
        <div id="product_reference">ref: <%= product.reference %></div>
        <div id="product_description"><p><%= product.reduced_description %></p></div>
        <div id="product_price">Precio: <%= product.price %> €</div>
        <div id="product_links"><%= link_to 'Comprar', add_to_cart_path(product.id), :remote => true %>
        <!-- - <%= link_to 'Ver más', product%>-->
         - <%= link_to 'Ver más', product_path(product, :category_id => params[:category_id], :page => params[:page])%>
        <%if current_user && current_user.admin?%>
         - <%= link_to 'Editar', edit_product_path(product) %>
        <%end%>
        </a></div>
     </td>
    <% end %>
  </tr>
<%end %>
</table>
<hr>
<div id="product_price"><%= paginate @products %></div>
<br />

<%if current_user && current_user.admin?%>
<div id="product_links">
<%= link_to 'Crear Nuevo Producto', new_product_path %>
</div>
<%end%>

</div><!-- /home-nav -->
        <div id="home-sidebar-cart">
            <div class="home-sidebar-section">
                <h2>Mi cesta</h2>
                <p> Agregue productos pulsando el enlace de <strong>"Comprar"</strong> para añadirlos a su cesta de la compra.</p>
                <p>Una vez tenga decido el total de su compra proceda a completarla usando <strong>"Finalizar"</strong></p>
                <div id="asinc_cart">
                 <%if session[:cart]%>
                  <%= render "cart" %>
                 <%end%>
                </div>
            </div>
            
        </div><!-- home-sidebar -->
    </div><!-- /home-content -->
</div><!-- /home-content-wrapper -->

app/views/products/listing.html.erb
<div id="home-content-wrapper-bar">

<div id="separator"></div>
<div id="home-content-header-thinest">
<p class="intro-message"><strong>Listado de Productos</strong></p>
</div>

<div id="home-content">

<table class="battle-table" border="0" width="70%">
  <tr>
    <th>Nombre</th>
    <th>Referencia</th>
    <th>¿Disponible?</th>
    <th>Precio (sin IVA)</th>
    <th>Num. de categorías</th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%=product.name%></td>
    <td><%=product.reference%></td>
    <td><%=product.st_availability%></td>
    <td><%=product.price%> €</td>
    <td><%=product.categories.count%></td>
    <td><%= link_to 'Modificar', edit_product_path(product) %></td>
    <td><%= link_to 'Eliminar', product, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
  </tr>
<% end %>
</table>

</div>
<hr> 
<div id="product_links">
<%if current_user && current_user.admin?%>
Opciones: <%= link_to 'Nuevo Producto', new_product_path %> / <%=link_to 'Panel', :controller => 'authentication', :action => 'sign_in'%>
<%end%>
</div>
<div id="product_links"><%= link_to '< Ir a la tienda', products_path %></div>
</div>

app/views/products/new.html.erb
<div id="home-content-wrapper">
<!-- /home-content-header -->

  <div id="home-content">

   <h1>Nuevo producto:</h1>

    <%= render 'form' %>

   </div><!-- /home-content -->

<div id="product_links">
<%= link_to 'Lista de productos', :controller => 'products', :action => 'listing' %>
</div>
</div><!-- /home-content-wrapper -->

app/views/products/purchase.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
    <p class="intro-message"><strong>Detalle de su pedido:</strong></p>
</div><!-- /home-content-header -->

  <div id="home-content">
    <div id="home-nav">
      <%if session[:cart].nil?%>
      <div class="home-nav-section-wideend last">
        <h1>No hay productos en su cesta</h1>
        <p>No hay productos almacenados en su cesta de la compra. Asegúrese de revisar su cesta (en la parte izquierda de 
          la sección de <%= link_to 'productos', products_path %>) y confirmar que aparecen ahí sus productos seleccionados.</p>
        <p>Revise tambíen que su navegador tenga habilitadas las cookies pues son necesarias momentáneamente para completar su pedido.</p>
      </div>
      <%else%>
        <%= form_tag :action => 'end_purchase' do%>
         <table class="order_sheet" border="1" width="80%">
          <tr><th>Producto</th><th align="center">Unidades</th><th align="center">Precio unitario</th><th align="right">Total por producto</th></tr>
          <%
          total_amount   = 0
          product_amount = 0
          session[:cart].items.each_key{|prod_id| 
            p = Product.find(prod_id)
            u = session[:cart].items[prod_id]
            product_amount = p.price * u.to_i
            total_amount += product_amount
            %>
            <tr><td><%=p.name%></td><td align="center"><%=u.to_s%></td><td align="center"><%=p.price%>€</td><td align="right"><%=product_amount%>€</td></tr>
          <%}%>
          <tr><td colspan="2" style="border-width: 0px;"></td><td align="right"><strong>Base:</strong></td><td align="right"><strong><%=total_amount%>€</strong></td></tr>
          <tr><td colspan="2" style="border-width: 0px;"></td><td align="right"><strong>IVA (<%=Product.IVA%>%):</strong></td><td align="right"><strong><%= '%.2f' % Product.IVA_amount(total_amount)%>€</strong></td></tr>
          <tr><td colspan="2" style="border-width: 0px;"></td><td align="right"><strong>Total:</strong></td><td align="right"><div id="product_price"><%= '%.2f' % Product.amount_with_tax(total_amount)%>€</div></td></tr>
        </table>
    
        <div id="separator"></div>

        <div id="order_form">
          <h1>Datos personales</h1>
          <p>Rellene todos los campos del siguiente formulario:</p>
          <label>Nombre y apellidos:</label>
          <%=text_field_tag 'nombre'%>

          <label>Dirección de envío:</label>
          <%=text_field_tag 'direccion'%>

          <label>Email de contacto:</label>
          <%=text_field_tag 'email'%>

          <label>Teléfono de contacto:</label>
          <%=text_field_tag 'telefono'%>

          <label>NIF:</label>
          <%=text_field_tag 'nif'%>

          <%=submit_tag "Confirmar pedido"%>
        </div>
      <%end%>
    <%end%>
    <div id="separator"></div>

    <div id="product_links">
        <%= link_to 'Continuar añadiendo productos', products_path %>
    </div>
    </div><!-- /home-nav -->
  
    <div id="home-sidebar">
            <div class="home-sidebar-section">
                <h2>Finalizar la compra</h2>
                <p>Puede <%= link_to 'continuar añadiendo productos', products_path %> y volver más tarde a esta página. </p>
                <p>Recuerde que en su <%= link_to 'Cesta', products_path %> puede sumar o restar unidades de un producto en su pedido (Usando los signos + y -).</p>
                <p>Una vez tenga decidido el total de su pedido, complételo pulsando el botón <strong>"Confirmar pedido"</strong></p>
                <p>Recuerde rellenar todos sus datos personales para poder ponernos en contacto con usted.</p>
                <p>Una vez completado el pedido, le remitiremos las instrucciones necesarias para efectuar el pago mediante <strong>transferencia bancaria</strong>.</p>
            </div>
            
     </div>

  </div><!-- /home-content -->

</div><!-- /home-content-wrapper -->

app/views/products/remove_from_cart.js.erb
$('#asinc_cart').html('<%=j render partial: 'products/cart'%>')

app/views/products/show.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
    <p id="notice"><%= notice %></p>
    <p class="intro-message"><strong><%= @product.name %></strong><br>
      ref: <%= @product.reference %></p>
</div><!-- /home-content-header -->

  <div id="home-content">
    <div id="home-nav">
      <div class="home-nav-section-wide">
        <%= image_tag(@product.image_path, :size => "250x250")%>
      </div>
      
      <div class="home-nav-section-wideend last">
        <p><%= @product.description %></p>
        <div id="product_price">Precio: <%= @product.price %> €</div>
      </div>
      <div id="product_links"><%= link_to 'Comprar', add_to_cart_path(@product.id), :remote => true  %> - <%= link_to 'Volver atrás', products_path(:category_id => params[:category_id], :page => params[:page]) %>
       <%if current_user && current_user.admin?%>
        - <%= link_to 'Editar', edit_product_path(@product) %>
        - <%= link_to 'Lista de productos', :controller => 'products', :action => 'listing' %>
       <%end%>
      </div>
    </div><!-- /home-nav -->
  
    <div id="home-sidebar-cart">
            <div class="home-sidebar-section">
                <h2>Mi cesta</h2>
                <p> Agregue productos pulsando el enlace de <strong>"Comprar"</strong> para añadirlos a su cesta de la compra.</p>
                <p>Una vez tenga decido el total de su compra proceda a completarla usando <strong>"Finalizar"</strong></p>
                <div id="asinc_cart">
                 <%if session[:cart]%>
                  <%= render "cart" %>
                 <%end%>
                </div>
            </div>
            
   </div>
  </div><!-- /home-content -->

</div><!-- /home-content-wrapper -->

app/views/products/thank_you.html.erb
<div id="home-content-wrapper">

<div id="home-content-header-thinest">
    <p class="intro-message"><strong>Pedido completado</strong></p>
</div>

  <div id="home-content">
    <div id="home-nav">      
      <div class="home-nav-section-wideend last">
        <p>Hemos recibido su solicitud. En el plazo más breve posible nos pondremos en contacto con usted para hacérselo llegar.</p>
        <p>No dude en contactar con Tecnisolar si tiene cualquier duda y cualquier comentario que hacernos llegar.</p>
        <p>Gracias por confiar en nuestro trabajo.</p>
      </div>
      <div id="separator"></div>
      <div id="product_links">
        <%= link_to 'Continuar navegando', products_path %>
      </div>
    </div><!-- /home-nav -->
  
  </div><!-- /home-content -->

</div><!-- /home-content-wrapper -->